builds:
- id: "oops"
  binary: oops
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/oops/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: mobingi
    name: oops
brews:
- tap:
    owner: mobingi
    name: homebrew-tap
  name: oops
  homepage: "https://github.com/mobingi/oops"
  description: "Kubernetes-native testing tool."
  folder: Formula
  install: |
    bin.install "oops"
  test: |
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
